# 02. Numpy

<p style="text-align: right;">
blackdew7@gmail.com<br>
Your name :
</p>

### 파이썬 실습시간 그 두번째!<br>

Numpy는 데이터 과학을 위한 핵심 라이브러리입니다.
고성능 다차원 배열과 배열 연산을 위한 유용한 도구를 제공합니다

#### 선행지식
1. Python 언어 기초.
2. 행렬에 대한 이해와 약간의 수학적 지식.

#### 실습목표
1. numpy를 이용하여 다양한 모양(shape)의 행렬 array를 만들 수 있습니다. 
2. numpy를 이용하여 다양한 행렬 연산을 수행할 수 있습니다. 
3. 2-d 어레이(혹은 그 이상)를 만들기. 
4. 1-d array를 2-d array로 만들기. 
5. 행렬 간의 곱셈.
6. csv파일 읽기. 
7. numpy array를 python list로 변환, python list를 numpy array로 변환
8. array shuffle, split, sampling (복원/비복원 둘 다.)


## 00. 라이브러리 불러오기

In [ ]:
import numpy as np

In [ ]:
data = np.genfromtxt("./resources/graduate_apply.csv", delimiter=",", names=True)
print(type(data))
print(data.shape)


In [ ]:
import numpy
data1 = numpy.genfromtxt("./resources/graduate_apply.csv", delimiter=",", names=True)
print(type(data1))
print(data1.shape)

In [ ]:
from numpy import genfromtxt as ggg
data2 = ggg("./resources/graduate_apply.csv", delimiter=",", names=True)
print(type(data2))
print(data2.shape)

In [ ]:
# 유용한 라이브러리
import time
import os

print(time.clock())
print(os.getcwd())

In [ ]:
# 유용한 라이브러리 02

%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

img = mpimg.imread('https://upload.wikimedia.org/wikipedia/commons/a/a4/TensorFlowLogo.png')
imgplot = plt.imshow(img)


## 01. Arrays 생성

In [ ]:
# Numpy 배열 생성하기

# rank 1 array 생성
a = np.array([1, 2, 3])
print(type(a))            # "<class 'numpy.ndarray'>"
print(a.shape)            # "(3,)"
print(a[0], a[1], a[2])   # "1 2 3"

# 값 변경
a[0] = 5
print(a)                  # "[5, 2, 3]"

# rank 2 array 생성
b = np.array([[1, 2, 3], 
              [4, 5, 6]])
print(b.shape)                     # "(2, 3)" (* 주의: 3x2 행렬)
print(b[0, 0], b[0, 1], b[1, 0])   # "1 2 4"


### reshape

In [ ]:
# reshape
c = np.reshape(b, (3, 2))
print(c.shape)                     # "(3, 2)" (* 주의: 2x3 행렬)

# 64 * 64 * 3
arr = np.zeros((64, 64, 3))
print(arr.shape)

b = arr.reshape(64 * 64, 3) 
print(b.shape)

# -1은 1차와 2차의 크기를 16과 16으로 맞추고 남은 나머지라는 뜻입니다. 
c = arr.reshape(16, 16, -1) 
print(c.shape) 
# (64 * 64 * 3) / (16 * 16) = 48이므로 배열의 세 번째 차원의 크기는 48이 됩니다.


### 여러가지 array 생성함수

In [ ]:
# Numpy는 배열을 생성하는 다양한 함수를 제공합니다.

# 0으로 채워진 array 생성
a = np.zeros((2, 2))
print(a)              # "[[ 0.  0.]
                      #   [ 0.  0.]]"

# 1로 채워진 array 생성
b = np.ones((1, 2))
print(b)              # "[[ 1.  1.]]"

# 특정 값으로 채워진 array 생성
c = np.full((2, 2), 7.)  
print(c)               # "[[ 7.  7.]
                       #   [ 7.  7.]]"

# 2x2 단위 행렬(identity matrix) 생성
d = np.eye(2)
print(d)              # "[[ 1.  0.]
                      #   [ 0.  1.]]"

# 랜덤값으로 채운 array 생성
e = np.random.random((2, 2))
print(e)

### 실습

In [ ]:
a = [1, 2, 3, 4, 5, 6]

# a를 가지고 numpy array np_01을 생성하시오
np_01 = 

# np_01의 shape를 확인하시오.

# np_01의 shape를 (6, 1)로 변환하여 np_02에 넣으세요. 

# np_01의 shape를 (1, 6)로 변환하여 np_03에 넣으세요. 

# np_01의 shape를 (-1, 2)로 변환하여 np_04에 넣으세요. 

# np_01, np_02, np_03, np_04의 모양을 출력하시고 shape와 실제 값의 모양을 확인하세요. 

# 랜덤값으로 채운 (28, 28) numpy array를 생성하여 nmist_sample 변수에 담으세요.


## 02. Array Indexing - Slice

In [ ]:
# 다음의 shape을 가지는 array 생성
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# shape (3, 4) - 4x3 행렬

# Slice를 이용하여 하위 배열 잘라내기.
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# 배열의 조각을 수정하면 원래 배열이 수정됩니다.
print(a[0, 1])   # "2"
b[0, 0] = 77     # b[0, 0] = a[0, 1]
print(a[0, 1])   # "77"

In [ ]:
# 다음의 shape을 가지는 array 생성
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 데이터에 액세스하는 두 가지 방법.

# 행
# 1. 정수 인덱스와 슬라이스를 섞으면 더 낮은 순위의 배열이 생성됩니다. 
row_r1 = a[1, :]             # Rank 1
print(row_r1, row_r1.shape)  # "[5 6 7 8] (4,)"

# 2. 슬라이스만 사용하면 원래 배열과 동일한 순위의 배열이 생성됩니다.
row_r2 = a[1:2, :]           # Rank 2
print(row_r2, row_r2.shape)  # "[[5 6 7 8]] (1, 4)"

# 열
col_r1 = a[:, 1]
print(col_r1, col_r1.shape)  # "[ 2  6 10] (3,)"

col_r2 = a[:, 1:2]
print(col_r2, col_r2.shape)  # "[[ 2]
                             #   [ 6]
                             #   [10]] (3, 1)"

In [ ]:
# Integer array indexing
a = np.array([[1, 2], [3, 4], [5, 6]])
b = a[[0, 1, 2]]

# "[1 4 5]"
print(a[[0, 1, 2], [0, 1, 0]])                
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

# 같은 위치 데이터를 여러번 사용할 수 있음
# "[2 2]"
print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))  

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a)  # "array([[ 1,  2,  3],
          #         [ 4,  5,  6],
          #         [ 7,  8,  9],
          #         [10, 11, 12]])"

# element 선택 방식
b = np.arange(4)
c = np.array([0, 2, 0, 1])
print(a[b, c])  # "[ 1  6  7 11]"

# 선택된 모든 element를 변경
a[b, c] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

In [ ]:
# Boolean array indexing

a = np.array([[1, 2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(bool_idx)      # "[[False False]
                     #   [ True  True]
                     #   [ True  True]]"

print(a[bool_idx])  # "[3 4 5 6]"
print(a[a > 2])     # "[3 4 5 6]"

### 실습

In [ ]:
# 다음의 shape을 가지는 numpy array를 생성하여 np_arr 변수에 담으세요
# [[  1  2  3]
#  [  4  5  6]
#  [  7  8  9]
#  [ 10 11 12]]


# np_arr의 shape를 확인하세요. 

# np_arr의 3행의 데이터를 낮은 순위의 배열로 출력하세요.
# [7 8 9]

# np_arr의 2열의 데이터를 낮은 순위의 배열로 출력하세요.
# [2 5 8 11]

# 아래의 출력문이 어떤 값을 출력할 지 추측한 후에 결과를 확인하세요.
print(np_arr[[0, 1, 2, 3], [1, 0, 1, 2]])

# 위의 실습에서 선택된 element 값을 모두 2배로 만드세요.

# np_arr을 출력해 봅니다.

# np_arr의 element중에 3의 배수인 element만 찾습니다. (3의 배수 찾는 법: x % 3 == 0)


## 03. Data 변환

In [ ]:
x = np.array([1, 2])
print(x.dtype)             # "int64"

x = np.array([1.0, 2.0])
print(x.dtype)             #"float64"

x = np.array([1, 2], dtype=np.int32)   # 강제로 데이터 형식 지정
print(x.dtype)                         # "int32"

In [ ]:
# Numpy Array
x = np.array([1, 2])
print(type(x))             # <class ‘numpy.ndarray’>

# numpy.ndarray to list
y = x.tolist()
print(y)            	   # [1, 2]
Print(type(y))             # <class ‘list’>

## 04. Array Math

In [ ]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# array 더하기
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# array 빼기
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# array 곱하기
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# array 나누기
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# array 제곱
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

In [ ]:
# 행렬곱

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# (1, 2) * (1, 2), 219
print(9 * 11 + 10 * 12)
print(v.dot(w))
print(np.dot(v, w))

# (2, 2) * (1, 2), rank 2 array
print("(1, 1): %d" % (1 * 9 + 2 * 10))
print("(1, 2): %d" % (3 * 9 + 4 * 10))
print(x.dot(v))
print(np.dot(x, v))

# (2, 2) * (2, 2), rank 2 array
# [[19 22]
#  [43 50]]
print("(1, 1): %d" % (1 * 5 + 2 * 7))
print("(1, 2): %d" % (1 * 6 + 2 * 8))
print("(2, 1): %d" % (3 * 5 + 4 * 7))
print("(2, 2): %d" % (3 * 6 + 4 * 8))
print(x.dot(y))
print(np.dot(x, y))

In [ ]:
x = np.array([[1, 2], [3, 4]])

# 합산
print(np.sum(x))          # "10"

# 열 합산
print(np.sum(x, axis=0))  # "[4 6]"

# 행 합산
print(np.sum(x, axis=1))  # "[3 7]"

In [ ]:
x = np.array([[1, 2], [3, 4]])
print(x)    # "[[1 2]
            #   [3 4]]"

# 전치 행렬
print(x.T)  # "[[1 3]
            #   [2 4]]"

x = np.array([1, 2, 3, 4], ndmin=2) # ndmin 없이 해보기
print(x)   	    # "[[1 2 3 4]]"
print(x.shape)  # (1, 4)

# 전치 행렬
print(x.T)  # "[[1]
            #   [2]
            #   [3]
            #   [4]]”
            
# rank 1 에서는 변화가 없음
v = np.array([1,2,3])
print(v)    # "[1 2 3]"
print(v.T)  # "[1 2 3]"

### 실습

In [ ]:
# 랜덤값으로 채운 (4, 3) numpy array를 생성하여 rand 변수에 담으세요.

# rand를 출력하세요.

# rand를 열 방향으로 합산하세요.

# rand를 행 방향으로 합산하세요.

# rand의 전치 행렬을 출력하세요.

## 05. Broadcasting

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

# x와 같은 shape의 0행렬 생성
y = np.empty_like(x)

# x의 행과 v의 모양이 같으므로 각 행에 v를 더한다.
for i in range(4):
    y[i, :] = x[i, :] + v

# y에 들어있는 결과 확인
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

# v를 여러개 쌓아 큰 배열의 모양으로 배열을 만든다.
vv = np.tile(v, (4, 1))
print(vv)                 # "[[1 0 1]
                          #   [1 0 1]
                          #   [1 0 1]
                          #   [1 0 1]]"
y = x + vv
print(y)    # "[[ 2  2  4
            #   [ 5  5  7]
            #   [ 8  8 10]
            #   [11 11 13]]"

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # broadcasting, v를 x의 각 행에 더한다.
print(y)   # "[[ 2  2  4]
           #   [ 5  5  7]
           #   [ 8  8 10]
           #   [11 11 13]]"

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
v = np.array([1, 2, 3])  # shape (3,)
w = np.array([4, 5])     # shape (2,)

print('------')
print(x)
print(x * 2)
# [[ 2  4  6]
#  [ 8 10 12]]

print('------')
print(x + v)
# [[2 4 6]
#  [5 7 9]]

print('------')
print(v)
print(np.reshape(v, (3, 1)))
print(w)
# 1x3 행렬 * 2x1 행렬 => 2x3 행렬
print(np.reshape(v, (3, 1)) * w)
# [[ 4  5]
#  [ 8 10]
#  [12 15]]

print('------')
print(x)
print(x.T)
print(w)
print(x.T + w)
print((x.T + w).T)
# [[ 5  6  7]
#  [ 9 10 11]]

print('------')
print(x)
print(np.reshape(w, (2, 1)))
print(x + np.reshape(w, (2, 1)))

### shuffle

In [ ]:
data = np.genfromtxt("./resources/graduate_apply.csv", delimiter=",", names=True)

print(data[0:10])

# Shuffle
np.random.shuffle(data)

print(data[0:10])

### split

In [ ]:
# Split
s1, s2, s3, s4 = data[:100], data[100:200], data[200:300], data[300:]
print(len(s1))
print(s1)
print(len(s2))
print(len(s3))
print(len(s4))


### 실습

In [ ]:
# ./resources/graduate_apply.csv 파일을 읽어서 apply 변수에 담으세요. 

# apply의 element 갯수를 확인하세요. (400)

# apply의 데이터 중 0 ~ 300 까지의 행은 train 변수에, 300 ~ 마지막 까지의 행은 test 변수에 담으세요.

# train에 담겨있는 데이터를 suffle 하세요.


## Numpy Documentation

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the <a href="http://docs.scipy.org/doc/numpy/reference/">numpy reference</a> to find out much more about numpy.